# Generated by Django 5.0.8 on 2024-08-11 04:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page', verbose_name='Introduction or Summary')),
                ('body', wagtail.fields.StreamField([('heading_block', 2), ('highlight_block', 6), ('paragraph_block', 7), ('image_block', 11), ('block_quote', 14), ('embed_block', 15), ('two_column_block', 16)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'require': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('heading_size', 1)]], {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('normal', 'regular'), ('font-style : italic;', 'italic'), ('font-weight: bold;', 'bold'), ('font-style : italic; font-weight: bold;', 'bold-italic')]}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 512}), 5: ('wagtail.blocks.ListBlock', (4,), {'blank': True, 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('format', 3), ('highlight_items', 5)]], {'icon': 'italic'}), 7: ('wagtail.blocks.RichTextBlock', (), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'require': True}), 9: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Specify the title of the image.', 'max_length': 255, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Specify the attribution of the image.', 'max_length': 255, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 8), ('caption', 9), ('attribution', 10)]], {}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. John Doe.', 'max_length': 255, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 12), ('attribution', 13)]], {}), 15: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert an embed URL like a video from Youtube.'}), 16: ('wagtail.blocks.StreamBlock', [[('paragraph_block', 7), ('image_block', 11), ('block_quote', 14), ('embed_block', 15)]], {'max_num': 2, 'min_num': 2})})),
                ('feature_image', models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='feature image')),
                ('image', models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='hero image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
